GET http://127.0.0.1:8080/api/film_category HTTP/1.1

###
GET http://127.0.0.1:8080/api/film HTTP/1.1

###
GET http://127.0.0.1:8080/api/film/22

###
POST http://127.0.0.1:8080/api/film HTTP/1.1
Content-Type: application/json

{
    "name": "Mamat123",
    "title": "Batman",
    "category_id": 8
}

###
PUT http://127.0.0.1:8080/api/film HTTP/1.1
Content-Type: application/json

{
    "id": 22,
    "name": "Bobohp2",
    "title": "Shaolin",
    "category_id": 1
}

###
DELETE http://127.0.0.1:8080/api/film HTTP/1.1
Content-Type: application/json

{
    "id": 22
}

###
GET http://127.0.0.1:8080/api/category HTTP/1.1

###
POST http://127.0.0.1:8080/api/category HTTP/1.1
Content-Type: application/json

{
    "category": "Thriller"
}