GET http://127.0.0.1:8080/film HTTP/1.1

###
GET http://127.0.0.1:8080/film/7

###
POST http://127.0.0.1:8080/film HTTP/1.1
Content-Type: application/json

{
    "name": "Mamat",
    "title": "Super Man",
    "category_id": 2
}

###
PUT http://127.0.0.1:8080/film HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "Bobohp",
    "title": "Shaolin",
    "category_id": 3
}Aqua Man

###
DELETE http://127.0.0.1:8080/film HTTP/1.1
Content-Type: application/json

{
    "id": 1
}

###
GET http://127.0.0.1:8080/category HTTP/1.1

###
POST http://127.0.0.1:8080/category HTTP/1.1
Content-Type: application/json

{
    "category": "romance"
}