CREATE TABLE USERS (
  id   BIGSERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(50) NOT NULL,
  gender_id SERIAL NOT NULL,
  create_at TIMESTAMP NOT NULL,
  update_at TIMESTAMP,
  CONSTRAINT fk_gender FOREIGN KEY(gender_id) REFERENCES gender(id)
);

CREATE TABLE GENDER (
  id SERIAL PRIMARY KEY,
  gender VARCHAR(20) NOT NULL
);